### ISSUE TITLE
Mekanism v9

### ISSUE THREAD

**Issue by PossessedDevil** [MJRLegends/ComputerCraft-Programs#1]
Hi, I tried your programs and I've encountered problem I don't know what to do with, since I just discovered ComputerCraft.

I tried your Big Reactors program and that one works top notch, no problem.

But then I tried your Mekanism reactor program and its giving me this screen.

![image](https://user-images.githubusercontent.com/64764953/81072528-8e585f80-8ee6-11ea-9ba3-65420a3de5bc.png)

![image](https://user-images.githubusercontent.com/64764953/81072703-cf507400-8ee6-11ea-82ec-69b4abaa92f5.png)

**Comment by MJRLegends** [comment]
What mekanism version and what minecraft version

**Comment by MJRLegends** [comment]
Also is the modem connected to the fusion reactor controller.

Because it needs to be connected to a reactor logic adapter i believe

**Comment by PossessedDevil** [comment]
Minecraft version 1.12.2, running the ATM3 modpack.
Mekanism version 
![image](https://user-images.githubusercontent.com/64764953/81077823-c4e5a880-8eed-11ea-84fb-c4ff51f73e36.png)

Connected correctly to the logic adapter.
![image](https://user-images.githubusercontent.com/64764953/81077902-db8bff80-8eed-11ea-970f-f5c9701e23c2.png)

**Comment by MJRLegends** [comment]
Thanks i will take a look, i made these programs like 3/4 years ago so i except some issues might me there. Looks like its not finding the reactor

**Comment by MJRLegends** [comment]
Which ComputerCraft (Alpha offical build of ComputerCraft) or the CC: Tweaked (Tweaked is a fork of ComputerCraft)

**Comment by PossessedDevil** [comment]
![image](https://user-images.githubusercontent.com/64764953/81082984-4809fd00-8ef4-11ea-86f3-830400700c51.png)

**Comment by MJRLegends** [comment]
Ahh the ComputerCraft (Alpha offical build of ComputerCraft)

Ok try using CC: Tweaked (Tweaked is a fork of ComputerCraft) https://www.curseforge.com/minecraft/mc-mods/cc-tweaked

**Comment by PossessedDevil** [comment]
Do I replace ComputerCraft with it or just add it? It says it's a fork of CC so I'd think I just add it, but I want to be sure.

**Comment by MJRLegends** [comment]
Remove old jar and add CC: Tweaked one ye?

**Comment by PossessedDevil** [comment]
Aha yeah figured. For some reason somehow I downloaded the 1.14 version . . . 
Launching MC now, brb in 20 minutes.

**Comment by MJRLegends** [comment]
Ok i except it to still not work but im wondering if it will give same error

**Comment by MJRLegends** [comment]
I've found the issue, re install the program via my install program and it will work perfectly

**Comment by MJRLegends** [comment]
(Fixed in v1.0.3 of the Fusion Reactor Management(Mekanism 9+)

**Comment by PossessedDevil** [comment]
![image](https://user-images.githubusercontent.com/64764953/81088868-e188dd00-8efb-11ea-8a6a-ff4c11abfd27.png)

Yep it works now. Guess I'll keep the CC tweaked as well. 

Thank you~

**Comment by MJRLegends** [comment]
Ye CC tweaked is less buggy and more maintained for latest mc versions too
