### ISSUE TITLE
Quick fix for mekanism v10 MJRLegends Fusion Reactor Managment

### ISSUE THREAD

**Issue by magnusa2007** [MJRLegends/ComputerCraft-Programs#5]
Just fixed it  to work for mekanism v10
[https://pastebin.com/AtsgxY8T](https://pastebin.com/AtsgxY8T)
Run "pastebin get AtsgxY8T startup" on the advanced computer. (if its already installed do "delete startup")
Remember to add a 4x4 monitor and use modems to conect the computer to a fusion logic adapter.

**Comment by KalviPL** [comment]
While refreshing on the text monitor, it blinks @MJRLegends @magnusa2007

**Comment by magnusa2007** [comment]
> While refreshing on the text monitor, it blinks @MJRLegends @magnusa2007

can try and make it  use clearline instead
made it less blinky https://pastebin.com/AtsgxY8T

**Comment by MJRLegends** [comment]
Added a official Fusion Reactor Management Program Mekanism 10 program to my system
